export enum ERROR_CODES {
  // MAIN ERRORS
  ERROR_TOKEN_AUTH_IS_NOT_VALID = 'ERROR_TOKEN_AUTH_IS_NOT_VALID',
  ERROR_TOKEN_REFRESH_IS_NOT_VALID = 'ERROR_TOKEN_REFRESH_IS_NOT_VALID',
  ERROR_USER_EXIST = 'ERROR_USER_EXIST',
  ERROR_USER_NOT_EXIST = 'ERROR_USER_NOT_EXIST',
  // CARDS SETS ERRORS
  ERROR_CARD_SET_EXIST = 'ERROR_CARD_SET_EXIST',
  ERROR_EXCEEDED_LIMIT_CARDS_SETS = 'ERROR_EXCEEDED_LIMIT_CARDS_SETS',
  // CARDS
  ERROR_EXCEEDED_LIMIT_CARDS_IN_CARD_SET = 'ERROR_EXCEEDED_LIMIT_CARDS_IN_CARD_SET',
  // LEARNING ERRORS
  ERROR_LEARNING_SESSION_IS_NOT_EXIST = 'ERROR_LEARNING_SESSION_IS_NOT_EXIST',
  ERROR_LEARNING_SESSION_ALREADY_EXIST = 'ERROR_LEARNING_SESSION_ALREADY_EXIST',
  ERROR_OUT_OF_CARDS = 'ERROR_OUT_OF_CARDS',
  ERROR_CARD_IS_NOT_EXIST = 'CARD_IS_NOT_EXIST',
  // RESET PASSWORD
  CONFIRMATION_KEY_IS_NOT_CORRECT = 'CONFIRMATION_KEY_IS_NOT_CORRECT',
}

export default ERROR_CODES;
