const ErrorCodes = {
  // MAIN ERRORS
  ERROR_TOKEN_AUTH_IS_NOT_VALID: 'ERROR_TOKEN_AUTH_IS_NOT_VALID',
  ERROR_TOKEN_REFRESH_IS_NOT_VALID: 'ERROR_TOKEN_REFRESH_IS_NOT_VALID',
  ERROR_USER_EXIST: 'ERROR_USER_EXIST',
  ERROR_USER_NOT_EXIST: 'ERROR_USER_NOT_EXIST',
  // CARDS SETS ERRORS
  ERROR_CARD_SET_EXIST: 'ERROR_CARD_SET_EXIST',
  ERROR_CARDS_SETS_LIMIT: 'ERROR_CARDS_SETS_LIMIT',
  // CARDS
  ERROR_LIMIT_CARDS_IN_CARD_SET: 'ERROR_LIMIT_CARDS_IN_CARD_SET',
  // LEARNING ERRORS
  ERROR_OUT_OF_CARDS: 'ERROR_OUT_OF_CARDS',
  ERROR_CARD_IS_NOT_EXIST: 'CARD_IS_NOT_EXIST',
};

export default ErrorCodes;
