const ErrorCodes = {
  // MAIN ERRORS
  ERROR_TOKEN_AUTH_IS_NOT_VALID: 'ERROR_TOKEN_AUTH_IS_NOT_VALID',
  ERROR_TOKEN_REFRESH_IS_NOT_VALID: 'ERROR_TOKEN_REFRESH_IS_NOT_VALID',
  ERROR_USER_EXIST: 'ERROR_USER_EXIST',
  ERROR_USER_NOT_EXIST: 'ERROR_USER_NOT_EXIST',
  // CARDS ERRORS
  ERROR_CARD_SET_EXIST: 'ERROR_CARD_SET_EXIST',
  // LEARNING ERRORS
  ERROR_OUT_OF_CARD: 'ERROR_OUT_OF_CARD',
  ERROR_CARD_IS_NOT_EXIST: 'CARD_IS_NOT_EXIST',
};

export default ErrorCodes;
